import { Dimensions, StyleSheet } from "react-native";

export const { width: SCREEN_WIDTH } = Dimensions.get("window");

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#f8fafc' },
  scrollContainer: { paddingBottom: 40 },
  authContainer: { padding: 20, paddingTop: 40 },
  appLogoText: { fontSize: 24, fontWeight: '800', color: '#0f172a', textAlign: 'center' },
  authSubTitle: { fontSize: 13, color: '#64748b', textAlign: 'center', marginTop: 4, marginBottom: 24 },
  roleSelectionRow: { flexDirection: 'row', gap: 12, marginBottom: 20 },
  roleBox: { flex: 1, backgroundColor: '#ffffff', padding: 16, borderRadius: 12, alignItems: 'center', borderWidth: 1.5, borderColor: '#e2e8f0' },
  selectedRoleBox: { borderColor: '#4f46e5', backgroundColor: '#eef2ff' },
  roleEmoji: { fontSize: 26 },
  roleText: { fontSize: 13, fontWeight: '700', color: '#64748b', marginTop: 6 },
  selectedRoleText: { color: '#4f46e5' },

  custHeaderRow: { 
    flexDirection: 'row', 
    justifyContent: 'space-between', 
    alignItems: 'center', 
    paddingHorizontal: 16, 
    paddingVertical: 12, 
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f1f5f9'
  },
  menuIconBtn: { padding: 4 },
  appHeaderTitle: { fontSize: 16, fontWeight: '800', color: '#0f172a', textAlign: 'center' },
  locSubText: { fontSize: 10, color: '#16a34a', fontWeight: '600', textAlign: 'center' },
  gpsReloadBtn: { padding: 6, backgroundColor: '#eef2ff', borderRadius: 8 },

  customerProfileCard: { backgroundColor: '#f8fafc', padding: 14, borderRadius: 12, borderWidth: 1, borderColor: '#e2e8f0', marginBottom: 12 },
  customerAvatarImg: { width: 46, height: 46, borderRadius: 23 },
  customerAvatarPlaceholder: { width: 46, height: 46, borderRadius: 23, backgroundColor: '#4f46e5', justifyContent: 'center', alignItems: 'center' },
  customerAvatarText: { color: '#ffffff', fontSize: 18, fontWeight: '800' },
  customerProfileName: { fontSize: 14, fontWeight: '800', color: '#0f172a' },
  customerProfilePhone: { fontSize: 11, color: '#64748b', marginTop: 2 },
  customerMainTabsRow: { flexDirection: 'row', marginTop: 12, backgroundColor: '#e2e8f0', borderRadius: 8, padding: 3 },
  customerTabItem: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 4, paddingVertical: 7, borderRadius: 6 },
  activeCustomerTabItem: { backgroundColor: '#ffffff', elevation: 1 },
  customerTabText: { fontSize: 11, fontWeight: '600', color: '#64748b' },
  activeCustomerTabText: { color: '#4f46e5', fontWeight: '800' },

  subTabsContainer: { flexDirection: 'row', backgroundColor: '#ffffff', paddingHorizontal: 16, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#e2e8f0', gap: 10 },
  subTabBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', backgroundColor: '#f1f5f9', borderRadius: 8 },
  activeSubTabBtn: { backgroundColor: '#eef2ff', borderWidth: 1, borderColor: '#c7d2fe' },
  subTabText: { fontSize: 11, fontWeight: '600', color: '#64748b' },
  activeSubTabText: { color: '#4f46e5', fontWeight: '800' },

  searchBoxContainer: { 
    flexDirection: 'row', 
    alignItems: 'center', 
    backgroundColor: '#ffffff', 
    borderWidth: 1, 
    borderColor: '#e2e8f0', 
    borderRadius: 12, 
    paddingHorizontal: 12, 
    marginHorizontal: 16, 
    marginTop: 16,
    marginBottom: 16,
    elevation: 1 
  },
  searchInput: { flex: 1, paddingVertical: 10, fontSize: 13, color: '#0f172a' },

  flexHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  activeFilterBadge: { fontSize: 11, backgroundColor: '#eef2ff', color: '#4f46e5', fontWeight: '700', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6 },

  distanceBadge: { backgroundColor: '#f0fdf4', paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, alignSelf: 'flex-start', marginTop: 6, borderWidth: 1, borderColor: '#bbf7d0' },
  distanceBadgeText: { fontSize: 11, color: '#15803d', fontWeight: '700' },

  custShopCard: { backgroundColor: '#ffffff', borderRadius: 16, marginBottom: 18, overflow: 'hidden', elevation: 2, borderWidth: 1, borderColor: '#e2e8f0' },
  // Auto-generated banner styles
  autoBannerShell: { marginHorizontal: 0, marginBottom: 0, overflow: 'hidden', borderTopLeftRadius: 15, borderTopRightRadius: 15 },
  autoBannerShellCompact: { borderRadius: 12 },
  autoBanner: { height: 138, paddingHorizontal: 14, paddingVertical: 10, overflow: 'hidden', position: 'relative' },
  autoBannerGlowOne: { position: 'absolute', width: 150, height: 150, borderRadius: 75, right: -55, top: -75, opacity: 0.30 },
  autoBannerGlowTwo: { position: 'absolute', width: 120, height: 120, borderRadius: 60, left: -65, bottom: -80, opacity: 0.20 },
  autoBannerGridLineOne: { position: 'absolute', width: '75%', height: 1, backgroundColor: 'rgba(255,255,255,0.16)', right: -20, top: 48, transform: [{ rotate: '-10deg' }] },
  autoBannerGridLineTwo: { position: 'absolute', width: '65%', height: 1, backgroundColor: 'rgba(255,255,255,0.10)', right: -10, top: 82, transform: [{ rotate: '-10deg' }] },
  autoBannerTopRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', zIndex: 2 },
  autoBrandPill: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 7, paddingVertical: 4, borderRadius: 10, backgroundColor: 'rgba(0,0,0,0.18)' },
  autoBrandText: { fontSize: 8, fontWeight: '900', letterSpacing: 1 },
  autoTierPill: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 10, borderWidth: 1 },
  autoTierText: { fontSize: 8, fontWeight: '900', letterSpacing: 0.4 },
  autoBannerMainRow: { flex: 1, flexDirection: 'row', alignItems: 'center', zIndex: 2, marginTop: 4 },
  autoBannerTextBlock: { flex: 1, paddingRight: 10 },
  autoBannerShopName: { fontSize: 20, fontWeight: '900', letterSpacing: 0.2 },
  autoBannerCategory: { fontSize: 11, fontWeight: '700', marginTop: 2 },
  autoBannerStatsRow: { flexDirection: 'row', alignItems: 'center', marginTop: 8 },
  autoStatItem: { flexDirection: 'row', alignItems: 'center', gap: 3 },
  autoStatText: { color: '#ffffff', fontSize: 9, fontWeight: '800' },
  autoStatDivider: { width: 1, height: 12, backgroundColor: 'rgba(255,255,255,0.35)', marginHorizontal: 7 },
  autoBannerSubLabel: { color: 'rgba(255,255,255,0.82)', fontSize: 9, fontWeight: '600', marginTop: 5 },
  autoBannerProfileWrap: { width: 70, height: 70, borderRadius: 35, backgroundColor: '#ffffff', borderWidth: 3, borderColor: '#ffffff', overflow: 'visible', elevation: 5, justifyContent: 'center', alignItems: 'center', marginRight: 2 },
  autoBannerProfileImage: { width: '100%', height: '100%', borderRadius: 35 },
  autoBannerProfilePlaceholder: { width: '100%', height: '100%', borderRadius: 35, backgroundColor: '#f1f5f9', justifyContent: 'center', alignItems: 'center' },
  autoBannerCameraBadge: { position: 'absolute', right: -2, bottom: -2, width: 22, height: 22, borderRadius: 11, backgroundColor: '#4f46e5', borderWidth: 2, borderColor: '#ffffff', justifyContent: 'center', alignItems: 'center' },
  custCardBannerHeader: { height: 110, backgroundColor: '#6366f1', position: 'relative' },
  custCardBannerImg: { width: '100%', height: '100%' },
  custCardBannerPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#1e293b' },
  custBannerPlaceholderText: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  
  custCardProfileOverlay: { width: 56, height: 56, borderRadius: 28, backgroundColor: '#ffffff', position: 'absolute', bottom: -14, left: 16, borderWidth: 2, borderColor: '#ffffff', overflow: 'visible', justifyContent: 'center', alignItems: 'center', elevation: 3 },
  custCardProfileImg: { width: '100%', height: '100%', borderRadius: 28 },
  custCardProfilePlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center', backgroundColor: '#f1f5f9', width: '100%', borderRadius: 28 },
  
  starBadgeOverlay: { position: 'absolute', bottom: -6, backgroundColor: '#0f172a', flexDirection: 'row', alignItems: 'center', gap: 2, paddingHorizontal: 5, paddingVertical: 1, borderRadius: 10, borderWidth: 1, borderColor: '#334155' },
  starBadgeText: { color: '#ffffff', fontSize: 9, fontWeight: '800' },

  custCardBody: { paddingTop: 20, paddingHorizontal: 16, paddingBottom: 16 },
  custCardShopTitle: { fontSize: 16, fontWeight: '800', color: '#0f172a' },
  custCardAddress: { fontSize: 12, color: '#64748b', marginTop: 2 },
  custCardBadge: { backgroundColor: '#eef2ff', color: '#4f46e5', fontSize: 11, fontWeight: '700', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6, borderWidth: 1, borderColor: '#c7d2fe' },
  custCardDivider: { height: 1, backgroundColor: '#f1f5f9', marginVertical: 12 },

  innerServiceRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10 },
  innerServiceBorder: { borderTopWidth: 1, borderTopColor: '#f1f5f9' },
  custCardServiceTitle: { fontSize: 14, fontWeight: '700', color: '#1e293b' },
  custCardSpecialty: { fontSize: 11, color: '#4f46e5', marginTop: 2 },
  custCardMeta: { fontSize: 11, color: '#64748b', marginTop: 4 },
  custBookBtn: { backgroundColor: '#4f46e5', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8 },
  custBookBtnText: { color: '#ffffff', fontWeight: '700', fontSize: 12 },

  cartBarFloating: { position: 'absolute', bottom: 15, left: 16, right: 16, backgroundColor: '#0f172a', borderRadius: 12, paddingHorizontal: 16, paddingVertical: 12, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', elevation: 5 },
  cartCheckoutBtn: { backgroundColor: '#4f46e5', paddingHorizontal: 14, paddingVertical: 8, borderRadius: 8 },
  cartCheckoutBtnText: { color: '#ffffff', fontWeight: '700', fontSize: 12 },

  drawerBackdrop: { position: 'absolute', top: 0, bottom: 0, left: 0, right: 0, backgroundColor: 'rgba(15, 23, 42, 0.4)', zIndex: 99 },
  drawerContainer: { position: 'absolute', top: 0, bottom: 0, left: 0, width: SCREEN_WIDTH * 0.8, backgroundColor: '#ffffff', zIndex: 100, padding: 16, elevation: 10 },
  drawerDivider: { height: 1, backgroundColor: '#e2e8f0', marginVertical: 12 },
  drawerSectionTitle: { fontSize: 12, fontWeight: '800', color: '#94a3b8', textTransform: 'uppercase', marginBottom: 10 },
  drawerFilterItem: { flexDirection: 'row', alignItems: 'center', gap: 10, paddingVertical: 10, paddingHorizontal: 8, borderRadius: 8, marginBottom: 4 },
  activeDrawerFilterItem: { backgroundColor: '#eef2ff' },
  drawerFilterText: { fontSize: 13, color: '#475569', fontWeight: '600' },
  activeDrawerFilterText: { color: '#4f46e5', fontWeight: '800' },
  drawerLogoutBtn: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingVertical: 12, paddingHorizontal: 10, borderRadius: 8, backgroundColor: '#fef2f2', marginTop: 10 },
  drawerLogoutText: { color: '#dc2626', fontWeight: '700', fontSize: 13 },

  custTopBar: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginHorizontal: 16, marginTop: 12, marginBottom: 12 },
  welcomeText: { fontSize: 18, fontWeight: '800', color: '#0f172a' },
  logoutBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: '#fef2f2', paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, borderWidth: 1, borderColor: '#fecaca' },
  logoutBtnText: { color: '#dc2626', fontSize: 12, fontWeight: '700' },

  card: { backgroundColor: '#ffffff', marginHorizontal: 16, padding: 16, borderRadius: 12, marginBottom: 16, elevation: 1 },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#1e293b' },
  editModeBtn: { backgroundColor: '#eef2ff', paddingHorizontal: 10, paddingVertical: 5, borderRadius: 6, borderWidth: 1, borderColor: '#c7d2fe', flexDirection: 'row', alignItems: 'center' },
  editModeBtnText: { fontSize: 12, color: '#4f46e5', fontWeight: '700' },
  cancelEditBtn: { backgroundColor: '#f1f5f9', padding: 12, borderRadius: 8, alignItems: 'center', justifyContent: 'center' },
  cancelEditBtnText: { color: '#64748b', fontWeight: '700', fontSize: 13 },
  viewProfileContainer: { marginTop: 5 },
  viewRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  viewLabel: { width: 100, fontSize: 13, fontWeight: '700', color: '#64748b' },
  viewValue: { flex: 1, fontSize: 13, color: '#0f172a', fontWeight: '500' },
  label: { fontSize: 12, fontWeight: '700', color: '#475569', marginBottom: 4, marginTop: 8 },
  input: { borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 8, fontSize: 13, backgroundColor: '#f8fafc' },
  disabledInput: { backgroundColor: '#e2e8f0', color: '#64748b' },
  btn: { backgroundColor: '#4f46e5', padding: 12, borderRadius: 8, alignItems: 'center', marginTop: 15 },
  btnText: { color: '#ffffff', fontWeight: '700', fontSize: 14 },
  
  fbHeaderContainer: { height: 160, marginHorizontal: 16, marginBottom: 45, position: 'relative' },
  bannerBox: { height: 130, borderRadius: 12, backgroundColor: '#e2e8f0', overflow: 'hidden' },
  bannerImage: { width: '100%', height: '100%' },
  bannerPlaceholder: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  uploadText: { fontSize: 12, color: '#64748b', fontWeight: '700' },
  
  profileBox: { width: 80, height: 80, borderRadius: 40, backgroundColor: '#cbd5e1', position: 'absolute', bottom: -18, left: 20, borderWidth: 3, borderColor: '#ffffff', overflow: 'visible', justifyContent: 'center', alignItems: 'center', zIndex: 10, elevation: 4 },
  profileImage: { width: '100%', height: '100%', borderRadius: 40 },
  profilePlaceholder: { alignItems: 'center' },
  profileUploadText: { fontSize: 10, color: '#475569', fontWeight: '700' },

  starBadgeOverlayOwner: { position: 'absolute', bottom: -8, backgroundColor: '#0f172a', flexDirection: 'row', alignItems: 'center', gap: 3, paddingHorizontal: 7, paddingVertical: 2, borderRadius: 12, borderWidth: 1.5, borderColor: '#ffffff' },
  starBadgeTextOwner: { color: '#ffffff', fontSize: 10, fontWeight: '800' },

  shopHeaderInfo: { marginHorizontal: 16, marginBottom: 15 },
  shopTitleText: { fontSize: 18, fontWeight: '800', color: '#0f172a' },
  ownerStarBadgeInline: { flexDirection: 'row', alignItems: 'center', gap: 4, backgroundColor: '#fef9c3', paddingHorizontal: 8, paddingVertical: 2, borderRadius: 6, borderWidth: 1, borderColor: '#fef08a' },
  shopCategoryText: { fontSize: 12, color: '#64748b', marginTop: 2 },

  tabContainer: { flexDirection: 'row', marginHorizontal: 16, marginBottom: 20, backgroundColor: '#f1f5f9', borderRadius: 14, padding: 4, borderWidth: 1, borderColor: '#e2e8f0' },
  tabBtn: { flex: 1, paddingVertical: 10, alignItems: 'center', justifyContent: 'center', borderRadius: 10, flexDirection: 'column', gap: 4 },
  activeTabBtn: { backgroundColor: '#ffffff', elevation: 2 },
  tabText: { fontSize: 11, color: '#64748b', fontWeight: '600' },
  activeTabText: { color: '#4f46e5', fontWeight: '800' },
  tabWithBadgeRow: { position: 'relative', alignItems: 'center' },
  tabBadge: { position: 'absolute', top: -4, right: -10, backgroundColor: '#ef4444', borderRadius: 10, minWidth: 16, height: 16, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 4 },
  tabBadgeText: { color: '#ffffff', fontSize: 9, fontWeight: '800' },

  categoryContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginVertical: 6 },
  catChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 15, backgroundColor: '#f1f5f9' },
  activeCatChip: { backgroundColor: '#4f46e5' },
  catChipText: { fontSize: 11, color: '#475569' },
  activeCatChipText: { color: '#ffffff', fontWeight: '700' },
  searchBtn: { backgroundColor: '#475569', padding: 10, borderRadius: 8, alignItems: 'center', marginVertical: 10 },
  searchBtnText: { color: '#ffffff', fontSize: 12, fontWeight: '700' },
  mapBox: { height: 160, borderRadius: 10, overflow: 'hidden', marginVertical: 10 },
  map: { width: '100%', height: '100%' },
  sectionHeader: { fontSize: 15, fontWeight: '700', color: '#1e293b' },
  serviceCard: { backgroundColor: '#ffffff', marginHorizontal: 16, padding: 12, borderRadius: 10, marginBottom: 10 },
  serviceHeaderRow: { flexDirection: 'row', justifyContent: 'space-between' },
  serviceTitle: { fontSize: 14, fontWeight: '700', color: '#0f172a' },
  servicePrice: { fontSize: 14, fontWeight: '700', color: '#16a34a' },
  specialtyText: { fontSize: 12, color: '#64748b', marginVertical: 4 },
  serviceFooterRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 5 },
  durationBadge: { fontSize: 11, color: '#4f46e5', fontWeight: '600' },
  deleteText: { fontSize: 11, color: '#ef4444', fontWeight: '700' },
  
  timeRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginTop: 5 },
  clockBtn: { backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#cbd5e1', padding: 10, borderRadius: 8, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 6 },
  clockBtnText: { fontSize: 12, fontWeight: '700', color: '#1e293b' },

  providerSubTabRow: { flexDirection: 'row', backgroundColor: '#e2e8f0', borderRadius: 10, padding: 3, marginBottom: 12 },
  providerSubTabBtn: { flex: 1, paddingVertical: 8, alignItems: 'center', borderRadius: 8 },
  activeProviderSubTabBtn: { backgroundColor: '#ffffff', elevation: 1 },
  providerSubTabText: { fontSize: 12, color: '#64748b', fontWeight: '600' },
  activeProviderSubTabText: { color: '#4f46e5', fontWeight: '800' },

  quickActionRow: { flexDirection: 'row', gap: 8, marginTop: 10, borderTopWidth: 1, borderTopColor: '#f1f5f9', paddingTop: 8 },
  actionBtnConfirm: { flex: 1, backgroundColor: '#4f46e5', paddingVertical: 8, borderRadius: 6, alignItems: 'center' },
  actionBtnComplete: { flex: 1, backgroundColor: '#16a34a', paddingVertical: 8, borderRadius: 6, alignItems: 'center', flexDirection: 'row', justifyContent: 'center', gap: 4 },
  actionBtnCancel: { backgroundColor: '#fee2e2', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 6, alignItems: 'center' },
  actionBtnText: { color: '#ffffff', fontSize: 11, fontWeight: '700' },
  actionCancelText: { color: '#dc2626', fontSize: 11, fontWeight: '700' },

  historyFilterRow: { flexDirection: 'row', gap: 6, marginBottom: 12, flexWrap: 'wrap' },
  historyFilterChip: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 15, backgroundColor: '#f1f5f9' },
  activeHistoryFilterChip: { backgroundColor: '#4f46e5' },
  historyFilterText: { fontSize: 11, color: '#64748b', fontWeight: '600' },
  activeHistoryFilterText: { color: '#ffffff', fontWeight: '800' },

  bookingCard: { backgroundColor: '#ffffff', padding: 14, borderRadius: 12, marginBottom: 12, borderWidth: 1, borderColor: '#e2e8f0', elevation: 1 },
  bookingHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10, paddingBottom: 8, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  customerName: { fontSize: 14, fontWeight: '700', color: '#0f172a' },
  statusBadge: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 6 },
  pendingBadge: { backgroundColor: '#fef3c7' },
  confirmedBadge: { backgroundColor: '#dcfce7' },
  statusBadgeText: { fontSize: 11, fontWeight: '700' },
  bookingDetailRow: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 4 },
  bookingDetail: { fontSize: 12, color: '#475569', fontWeight: '500' },
  
  doneAndRateBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', backgroundColor: '#16a34a', paddingVertical: 8, borderRadius: 8, marginTop: 12 },
  doneAndRateBtnText: { color: '#ffffff', fontWeight: '700', fontSize: 12 },

  emptyBox: { padding: 40, alignItems: 'center' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', padding: 20 },
  modalContent: { backgroundColor: '#ffffff', borderRadius: 16, padding: 20 },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#0f172a' },
  modalSubTitle: { fontSize: 13, color: '#4f46e5', fontWeight: '600', marginBottom: 10 },
  modalCartSummary: { backgroundColor: '#f8fafc', padding: 10, borderRadius: 8, marginVertical: 10, borderWidth: 1, borderColor: '#e2e8f0' },
  modalCartRow: { flexDirection: 'row', justifyContent: 'space-between', marginVertical: 2 },
  modalCartTotalRow: { flexDirection: 'row', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#e2e8f0', paddingTop: 6, marginTop: 6 },
  slotChip: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 8, backgroundColor: '#f1f5f9', marginRight: 8 },
  activeSlotChip: { backgroundColor: '#4f46e5' },
  slotChipText: { fontSize: 12, color: '#334155' },
  activeSlotChipText: { color: '#ffffff', fontWeight: '700' },
  modalActions: { flexDirection: 'row', gap: 10, marginTop: 15 },
  cancelBtn: { flex: 1, padding: 12, borderRadius: 8, backgroundColor: '#f1f5f9', alignItems: 'center' },
  cancelBtnText: { color: '#475569', fontWeight: '700' },
  confirmBtn: { flex: 1, padding: 12, borderRadius: 8, backgroundColor: '#4f46e5', alignItems: 'center' },
  confirmBtnText: { color: '#ffffff', fontWeight: '700' },

  starSelectionRow: { flexDirection: 'row', justifyContent: 'center', gap: 8, marginVertical: 12 },

  // V1.0 UI/UX upgrade styles
  authBrandRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 10, marginBottom: 6 },
  brandMark: { width: 42, height: 42, borderRadius: 14, backgroundColor: '#4f46e5', justifyContent: 'center', alignItems: 'center', elevation: 5 },
  roleIconCircle: { width: 48, height: 48, borderRadius: 16, backgroundColor: '#f1f5f9', justifyContent: 'center', alignItems: 'center' },
  roleIconCircleActive: { backgroundColor: '#6366f1', elevation: 3 },
  customerBrandWrap: { flexDirection: 'row', alignItems: 'center', gap: 7 },
  customerBrandMark: { width: 30, height: 30, borderRadius: 10, backgroundColor: '#6366f1', justifyContent: 'center', alignItems: 'center', elevation: 3 },
  categorySliderContent: { paddingHorizontal: 16, paddingBottom: 12, gap: 8 },
  modernFilterChip: { paddingHorizontal: 13, paddingVertical: 8, borderRadius: 18, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0', elevation: 1 },
  modernFilterChipActive: { backgroundColor: '#6366f1', borderColor: '#6366f1', elevation: 3 },
  modernFilterChipText: { fontSize: 11, fontWeight: '700', color: '#64748b' },
  modernFilterChipTextActive: { color: '#ffffff' },
  cardActionColumn: { alignItems: 'flex-end', gap: 7 },
  seeImagesBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 8, paddingVertical: 5, borderRadius: 10, backgroundColor: '#eef2ff', borderWidth: 1, borderColor: '#c7d2fe' },
  seeImagesText: { fontSize: 10, fontWeight: '800', color: '#4f46e5' },
  customerProfileCardFree: { backgroundColor: '#09090b', borderColor: '#27272a' },
  customerProfileCardPaid: { backgroundColor: '#b7791f', borderColor: '#f6d365', shadowColor: '#d4af37', shadowOpacity: 0.35, shadowRadius: 10 },
  customerProfileNameFree: { color: '#ffffff' },
  customerProfilePhoneFree: { color: '#a1a1aa' },
  customerProfileNamePaid: { color: '#fff8dc' },
  customerProfilePhonePaid: { color: '#fef3c7' },
  customerMembershipPill: { alignSelf: 'flex-start', marginTop: 5, paddingHorizontal: 7, paddingVertical: 3, borderRadius: 8, fontSize: 8, fontWeight: '900', overflow: 'hidden' },
  customerMembershipFree: { backgroundColor: '#27272a', color: '#d4d4d8' },
  customerMembershipPaid: { backgroundColor: '#f6d365', color: '#6b4600' },

  customerAvatarEditWrap: { position: 'relative' },
  customerCameraBadge: { position: 'absolute', right: -2, bottom: -2, width: 21, height: 21, borderRadius: 11, backgroundColor: '#6366f1', borderWidth: 2, borderColor: '#ffffff', justifyContent: 'center', alignItems: 'center' },
  modernSelectBtn: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingHorizontal: 12, paddingVertical: 11, borderRadius: 10, backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#cbd5e1', marginBottom: 5 },
  modernSelectText: { fontSize: 13, color: '#0f172a', fontWeight: '700', flex: 1 },
  businessImageRow: { flexDirection: 'row', gap: 10, marginTop: 5 },
  businessImagePicker: { flex: 1, height: 100, borderRadius: 12, borderWidth: 1, borderColor: '#cbd5e1', backgroundColor: '#f8fafc', justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  businessImageThumb: { width: '100%', height: '100%' },
  businessImageLabel: { position: 'absolute', bottom: 5, left: 6, backgroundColor: 'rgba(15,23,42,0.75)', color: '#ffffff', paddingHorizontal: 7, paddingVertical: 3, borderRadius: 7, fontSize: 10, fontWeight: '800' },
  fullShopImageWrap: { width: SCREEN_WIDTH - 64, height: 300, marginRight: 10, borderRadius: 14, overflow: 'hidden', backgroundColor: '#0f172a' },
  fullShopImage: { width: '100%', height: '100%', resizeMode: 'cover' },
  imageCaption: { position: 'absolute', left: 12, bottom: 10, color: '#ffffff', backgroundColor: 'rgba(15,23,42,0.7)', paddingHorizontal: 9, paddingVertical: 5, borderRadius: 8, fontWeight: '800', fontSize: 11 },
  dashboardAccent: { color: '#6366f1' },
  adminHeader: { paddingHorizontal: 16, paddingVertical: 14, backgroundColor: '#ffffff', borderBottomWidth: 1, borderBottomColor: '#e2e8f0', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  adminBrandRow: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  adminBrandMark: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#111827', justifyContent: 'center', alignItems: 'center' },
  adminTitle: { fontSize: 16, fontWeight: '900', color: '#0f172a' },
  adminSubTitle: { fontSize: 10, color: '#64748b', marginTop: 1 },
  adminCollectionRow: { paddingHorizontal: 16, paddingVertical: 10, gap: 7 },
  adminCollectionChip: { paddingHorizontal: 11, paddingVertical: 7, borderRadius: 16, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0' },
  adminCollectionChipActive: { backgroundColor: '#111827', borderColor: '#111827' },
  adminCollectionText: { fontSize: 10, fontWeight: '800', color: '#64748b' },
  adminCollectionTextActive: { color: '#ffffff' },
  adminToolbar: { flexDirection: 'row', gap: 8, paddingHorizontal: 16, paddingBottom: 8 },
  adminSearchBox: { flex: 1, flexDirection: 'row', alignItems: 'center', gap: 7, backgroundColor: '#ffffff', borderWidth: 1, borderColor: '#e2e8f0', borderRadius: 10, paddingHorizontal: 10 },
  adminSearchInput: { flex: 1, paddingVertical: 8, fontSize: 12, color: '#0f172a' },
  adminAddBtn: { width: 42, height: 42, borderRadius: 12, backgroundColor: '#6366f1', justifyContent: 'center', alignItems: 'center', elevation: 3 },
  adminDocCard: { backgroundColor: '#ffffff', borderRadius: 14, padding: 12, marginBottom: 10, borderWidth: 1, borderColor: '#e2e8f0' },
  adminDocTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 7 },
  adminDocId: { flex: 1, fontSize: 11, fontWeight: '900', color: '#111827', marginRight: 10 },
  adminDocActions: { flexDirection: 'row', gap: 6 },
  adminIconBtn: { width: 32, height: 32, borderRadius: 9, backgroundColor: '#eef2ff', justifyContent: 'center', alignItems: 'center' },
  adminIconBtnDanger: { width: 32, height: 32, borderRadius: 9, backgroundColor: '#fef2f2', justifyContent: 'center', alignItems: 'center' },
  adminDocPreview: { fontFamily: 'monospace', fontSize: 9, lineHeight: 14, color: '#475569', backgroundColor: '#f8fafc', padding: 8, borderRadius: 8 },
  adminJsonInput: { minHeight: 300, borderWidth: 1, borderColor: '#cbd5e1', borderRadius: 10, backgroundColor: '#0f172a', color: '#e2e8f0', padding: 12, fontFamily: 'monospace', fontSize: 11, textAlignVertical: 'top' },
  modalHeaderRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 4 },
  catalogOption: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 12, paddingHorizontal: 10, borderBottomWidth: 1, borderBottomColor: '#f1f5f9' },
  catalogOptionText: { fontSize: 13, fontWeight: '700', color: '#0f172a', flex: 1 },

  // External (OpenStreetMap) nearby-results fallback — intentionally muted /
  // undecorated styling so these never look like ServiceBazar providers.
  externalSectionHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 8, marginTop: 4 },
  externalSectionHeaderText: { fontSize: 11, fontWeight: '700', color: '#64748b' },
  externalResultCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: '#f8fafc', borderWidth: 1, borderColor: '#e2e8f0', borderStyle: 'dashed', borderRadius: 12, padding: 12, marginBottom: 8 },
  externalResultName: { fontSize: 13, fontWeight: '700', color: '#334155' },
  externalResultCategory: { fontSize: 11, color: '#94a3b8', marginTop: 1, textTransform: 'capitalize' },
  externalResultAddress: { fontSize: 11, color: '#64748b', marginTop: 3 },
  externalResultDistance: { fontSize: 11, color: '#4f46e5', fontWeight: '700', marginTop: 3 },
  externalViewMapBtn: { flexDirection: 'row', alignItems: 'center', gap: 4, paddingHorizontal: 10, paddingVertical: 7, borderRadius: 8, backgroundColor: '#eef2ff', borderWidth: 1, borderColor: '#c7d2fe' },
  externalViewMapBtnText: { fontSize: 10, fontWeight: '800', color: '#4f46e5' },
  externalDisclaimerText: { fontSize: 10, color: '#94a3b8', textAlign: 'center', marginTop: 4, marginBottom: 10, fontStyle: 'italic' },
});